version: "3.8"

networks:
  default:
    name: traefik

services:
  traefik:
    image: traefik:vacherin #2.8
    container_name: traefik
    restart: always
    volumes:
      - ./certs:/certs
      - ./conf:/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
##      - 443:443
      - 8080:8080
    command:
      - "--global.checkNewVersion=true"
      - "--accessLog=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log=true"
      - "--log.level=WARN"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik"
##      - "--providers.file.directory=/conf/"
##      - "--providers.file.watch=true"
#      - "--entryPoints.web.address=:80"
#      - "--entryPoints.web.forwardedHeaders.trustedIPs=192.168.0.0/16"
#      - "--entryPoints.web.forwardedHeaders.insecure=true"
##      - "--entryPoints.websecure.address=:443"
##      - "--entryPoints.websecure.forwardedHeaders.insecure=true"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
##      - "traefik.http.routers.traefik-http.rule=Host(`traefik.dashboard`)"
##      - "traefik.http.routers.traefik-http.entrypoints=web"
##      - "traefik.http.routers.traefik-http.middlewares=redirect-to-https"
#      - "traefik.http.routers.traefik.rule=Host(`traefik.dashboard`)"
#      - "traefik.http.routers.traefik.service=api@internal"
##      - "traefik.http.routers.traefik.entrypoints=websecure"
##      - "traefik.http.routers.traefik.tls=true"
